# Generated by Django 4.0.4 on 2022-05-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='user_status',
            new_name='org_status',
        ),
    ]
